# Stage 1 - Build < -------------------

FROM 3.6.3-jdk-11-slim as build

WORKDIR /workspace/app

COPY . .

RUN mvn clean package -DskipTests



# Stage 2 - Publish < -----------------

FROM openjdk:11 AS publish

VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency

EXPOSE 8080 8081

COPY --from=build /workspace/app/target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]